name: CI - Tests API Flask

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Installer les dépendances
        run: |
          pip install -r requirements.txt
          pip install pytest requests

      - name: Démarrer l'API Flask en arrière-plan
        run: |
          nohup python app.py > api.log 2>&1 &
        env:
          FLASK_ENV: testing

      - name: Attendre que l'API démarre
        run: sleep 10  # Attente de 10 secondes pour être sûr que l'API est bien lancée

      - name: Vérifier si l'API tourne
        run: |
          if ! curl -s http://127.0.0.1:5000/health; then
            echo "L'API ne tourne pas. Logs de l'API :"
            cat api.log
            exit 1
          fi

      - name: Lancer les tests
        run: pytest tests/test_api.py
