name: CI - Tests API Flask

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Installer les dépendances
        run: |
          pip install -r requirements.txt
          pip install pytest requests

      - name: Vérifier la présence des fichiers
        run: ls -la

      - name: Lancer les tests
        run: pytest tests/test_api.py
