name: CI - Tests API Flask

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Installer les dépendances
        run: |
          pip install -r requirements.txt
          pip install pytest requests

      - name: Démarrer l'API Flask en arrière-plan
        run: |
          python app.py &
        env:
          FLASK_ENV: testing

      - name: Attendre que l'API démarre
        run: sleep 5  # Attente de 5 secondes pour que l'API démarre

      - name: Lancer les tests
        run: pytest tests/test_api.py
